export const emojiCatalogSeed = [
  {
    symbol: "🌱",
    name: "First Sprout",
    rarity: "Common",
    biomes: ["Grass"],
    lore: "Scholars believe this sprout appears wherever the land decides to live again. Entire forests are said to have begun with a single one.",
  },
  {
    symbol: "🍃",
    name: "Whispering Leaf",
    rarity: "Common",
    biomes: ["Grass", "Forest"],
    lore: "When the wind is silent, some travelers swear this leaf still moves. They say it listens, not blows.",
  },
  {
    symbol: "🐛",
    name: "Dusk Crawler",
    rarity: "Common",
    biomes: ["Forest", "Swamp"],
    lore: "A creature bound to the soil. Ancient texts call it the keeper of beginnings and endings.",
  },
  {
    symbol: "🪨",
    name: "Timeworn Stone",
    rarity: "Common",
    biomes: ["Desert"],
    lore: "Carried by no one, owned by no one. This stone has watched empires rise and crumble into dust.",
  },
  {
    symbol: "💧",
    name: "Memory Drop",
    rarity: "Common",
    biomes: ["Water"],
    lore: "It holds reflections of skies long vanished. Some say staring too long shows forgotten shores.",
  },
  {
    symbol: "❄️",
    name: "Silent Flake",
    rarity: "Common",
    biomes: ["Snow"],
    lore: "Born without sound, gone without trace. Its silence is louder than storms.",
  },
  {
    symbol: "🔥",
    name: "Unbound Ember",
    rarity: "Common",
    biomes: ["Volcano"],
    lore: "A fragment of fire that refuses to die. Even cooled stone remembers its warmth.",
  },

  {
    symbol: "🌾",
    name: "Kingmaker Grain",
    rarity: "Uncommon",
    biomes: ["Grass"],
    lore: "Harvested fields like this once decided wars. Hunger bows to whoever controls it.",
  },
  {
    symbol: "🌲",
    name: "Watcher Pine",
    rarity: "Uncommon",
    biomes: ["Forest"],
    lore: "This tree grows where battles were fought. Its rings mark victories and regrets alike.",
  },
  {
    symbol: "🐍",
    name: "Suncoil Serpent",
    rarity: "Uncommon",
    biomes: ["Desert", "Swamp"],
    lore: "It basks beneath deadly suns and poisoned waters. Survival is its only language.",
  },
  {
    symbol: "🦀",
    name: "Ironclaw Drifter",
    rarity: "Uncommon",
    biomes: ["Water"],
    lore: "Its shell bears scars of tides and anchors. It adapts where others sink.",
  },
  {
    symbol: "🌫️",
    name: "Veil of Lost Paths",
    rarity: "Uncommon",
    biomes: ["Swamp"],
    lore: "Many enter. Few return. Those who do never walk the same way again.",
  },
  {
    symbol: "☃️",
    name: "Frostbound Effigy",
    rarity: "Uncommon",
    biomes: ["Snow"],
    lore: "Built by forgotten hands during a winter that never truly ended.",
  },

  {
    symbol: "🌵",
    name: "Bloodwater Cactus",
    rarity: "Rare",
    biomes: ["Desert"],
    lore: "Its core holds water so pure it saved caravans — and doomed those who fought over it.",
  },
  {
    symbol: "🌊",
    name: "Ocean’s Breath",
    rarity: "Rare",
    biomes: ["Water"],
    lore: "A wave that exhales and inhales. Sailors claim it chooses who returns.",
  },
  {
    symbol: "🧊",
    name: "Heart of Permafrost",
    rarity: "Rare",
    biomes: ["Snow"],
    lore: "Ice older than language itself. It remembers when the world stood still.",
  },
  {
    symbol: "🦠",
    name: "Rotborn Essence",
    rarity: "Rare",
    biomes: ["Swamp"],
    lore: "Decay made conscious. Without it, nothing new would grow.",
  },
  {
    symbol: "🌋",
    name: "Sleeping Calamity",
    rarity: "Rare",
    biomes: ["Volcano"],
    lore: "Its silence terrifies more than its eruption ever could.",
  },

  {
    symbol: "🦌",
    name: "Glimmerhart Stag",
    rarity: "Epic",
    biomes: ["Forest"],
    lore: "Those who follow it never find treasure — only themselves.",
  },
  {
    symbol: "🦂",
    name: "Ashveil Scorpion",
    rarity: "Epic",
    biomes: ["Desert"],
    lore: "Its venom does not kill immediately. It teaches patience through pain.",
  },
  {
    symbol: "🦑",
    name: "Deepmind Watcher",
    rarity: "Epic",
    biomes: ["Water"],
    lore: "It observes ships not as prey, but as passing thoughts.",
  },
  {
    symbol: "🧟",
    name: "Gravebound Walker",
    rarity: "Epic",
    biomes: ["Swamp"],
    lore: "Neither alive nor dead. It walks because the land remembers it.",
  },
  {
    symbol: "🐻",
    name: "Winter Tyrant",
    rarity: "Epic",
    biomes: ["Snow"],
    lore: "When it awakens, entire valleys fall silent in fear.",
  },

  {
    symbol: "🦅",
    name: "Horizon Judge",
    rarity: "Mythic",
    biomes: ["Grass", "Forest"],
    lore: "It sees lies as shadows. Truth bends its wings.",
  },
  {
    symbol: "🐋",
    name: "Songbearer Leviathan",
    rarity: "Mythic",
    biomes: ["Water"],
    lore: "Its call reshapes currents and memories alike.",
  },
  {
    symbol: "🧙",
    name: "The Pale Arcanist",
    rarity: "Mythic",
    biomes: ["Snow"],
    lore: "Magic obeys them not out of fear, but respect.",
  },
  {
    symbol: "🐲",
    name: "Ashborn Wyrm",
    rarity: "Mythic",
    biomes: ["Volcano"],
    lore: "Each scale remembers a civilization it burned.",
  },

  {
    symbol: "🦄",
    name: "Oathbound Unicorn",
    rarity: "Legendary",
    biomes: ["Grass"],
    lore: "It appears only when a promise is truly unbreakable.",
  },
  {
    symbol: "🐉",
    name: "Endless Sovereign",
    rarity: "Legendary",
    biomes: ["Volcano"],
    lore: "Time does not age it. Time learns from it.",
  },
  {
    symbol: "🧜",
    name: "Queen of Tides",
    rarity: "Legendary",
    biomes: ["Water"],
    lore: "Storms kneel when her song begins.",
  },
  {
    symbol: "👑",
    name: "Crown of Frozen Rule",
    rarity: "Legendary",
    biomes: ["Snow"],
    lore: "Every ruler who wore it vanished — except the crown.",
  },
  {
    symbol: "🌳",
    name: "Axis of Realms",
    rarity: "Legendary",
    biomes: ["Forest"],
    lore: "Roots beneath every biome. Leaves in worlds unseen.",
  },
];
